module.exports = {
	
	centerOfExcellence : "https://team.amer.mymetlife.com/Teams/developers/Lists/WAS 85 Discussion/Flat.aspx?RootFolder=%2FTeams%2Fdevelopers%2FLists%2FWAS%2085%20Discussion%2FWhere%20can%20i%20find%20the%20Governance%20Model&FolderCTID=0x01200200D0961C7E2728A84BACA217F63BA507E5"
	,communityOfPractice : "https://team.amer.mymetlife.com/Teams/developers/SiteAssets/WAS Dev Self Service.aspx"
	,template : function(e){		
		
		return "<div>" 
		+ "<b>" + e.projectManager +"</b>"
		+ "<br/>"   
		+ "<div><br/>Your WAS Development Environment (EAI code: "+e.eai+") is scheduled for conversion beginning "+e.convStartDate+". Your team is required to take following actions:</div>"
		+ "<ul>"
		+ "<li>"
		+ "Access Management: We recommend all software engineering teams confirm that they have appropriate access to their development environment. Contact IDAdmin to request MetNet group be added to the development box. The group must contain all developers who need access to the environment using personal MetNet ID."
		+ "</li>"
		+ "<li>"
		+ "Governance Model: We encourage all software engineering teams to review the governance model located in the <a href='"+this.centerOfExcellence+"'>Center of Excellence</a>."
		+ "</li>"
		+ "<li>"
		+ "Tools: We recommend installing BMC Middleware Automation before the training. Detailed installation instructions are available at the Center of Excellence site - FAQ \"BMA Installation Instructions.\""
		+ "</li>"
		+ "<li>"
		+ "Training: Training is available for all MetLife associates from Learning and Development. To access web-based training, go to My Learning and search for following modules to enroll:"
		+ "<ul>"
		+ "<li>BMC Middleware Automation 8.1: Fundamentals - Module 1 (MLG00978)</li>"
		+ "<li>BMC Middleware Automation 8.1: Fundamentals - Module 2 (MLG00979)</li>"
		+ "<li>BMC Middleware Automation 8.1: Fundamentals - Module 3 (MLG00980)</li>"
		+ "</ul>"
		+ "</li>"
		+ "<li>" 
		+ "Global Tracker Site: Go to the <a href='http://us1700368:9001/'>conversion tracker site</a>, locate your application instance, and click on Env. Signoff and Guideline Signoff button."
		+ "<ul><li style='color:Red'>"
		+ " Please note!!!  The link to the conversion tracker site is NOT " 
		+ "compatible with IE.  Please open in the Chrome browser for the appropriate user experience"
		+ "</li></ul>"
		+ "</li>"
		+ "<li><b>Finally, test your application to ensure all areas are functional.</b></li>"
		+ "</ul>"
		+ "<div>"
		+ "Train "+e.train+" is slated to conclude by "+e.tgtConvDate+". You must complete the above steps for successful conversion."
		+ "<br/>"
		+ "<br/>"
		+ "For questions, please connect with us on Developer Community - <a href='"+this.communityOfPractice+"'>WAS DEV Self Service community of practice</a>."
		+ "<div>"
		+ "<br/>"
		+ "<div>"
		+ "Thank you,"
		+ "<br/>"
		+ "Your Was Dev Migration Team"
		+ "</div>"
		+ "</div>";
	}

};